In [2]:
import numpy as np

arr = np.array([20,40,60,80])
print(np.append(arr,90))

[20 40 60 80 90]


In [3]:
arr = np.array([20,40,60,80])
print(np.append(arr,[90,100]))

[ 20  40  60  80  90 100]


In [4]:
print(np.insert(arr,1,50)) #array,index,value

[20 50 40 60 80]


In [6]:
arr = np.array([[20,40],[60,80]])
print(np.insert(arr,1,[50,60], axis=1))

[[20 50 40]
 [60 60 80]]


In [7]:
arr = np.array([[20,40],[60,80]])
print(np.insert(arr,1,[50,60], axis=0))

[[20 40]
 [50 60]
 [60 80]]


In [9]:
print(arr)
print(np.delete(arr,1))

[[20 40]
 [60 80]]
[20 60 80]


In [10]:
print(arr)
print(np.delete(arr,1,axis=0))

[[20 40]
 [60 80]]
[[20 40]]


In [11]:
print(arr)
print(np.delete(arr,1,axis=1))

[[20 40]
 [60 80]]
[[20]
 [60]]
