In [2]:
import numpy as np 

a = [30,40,50,60]
arr = np.array(a)
print(arr)

[30 40 50 60]


In [3]:
print(arr.shape)

(4,)


In [4]:
print(len(arr))

4


In [5]:
print(np.size(arr))

4


In [6]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [7]:
print(arr.astype(float))

[30. 40. 50. 60.]


In [8]:
print(arr.astype(str))

['30' '40' '50' '60']


In [11]:
a = [[30,40,50,60],[70,80,90,100]]
arr = np.array(a)
print(arr)
print(arr.shape)  #rows,column
print(len(arr))   #number of nested value
print(np.size(arr))  #number of element
print(type(arr))  #datatype of variable
print(arr.dtype)  #datatype of array
print(arr.astype(float)) #conversin of datatype

[[ 30  40  50  60]
 [ 70  80  90 100]]
(2, 4)
2
8
<class 'numpy.ndarray'>
int64
[[ 30.  40.  50.  60.]
 [ 70.  80.  90. 100.]]
