In [1]:
import numpy as np
arr = np.array([20,40,60,70])
print(np.sum(arr))

190


In [2]:
print(np.max(arr))

70


In [3]:
print(np.min(arr))

20


In [4]:
print(np.size(arr))

4


In [5]:
print(np.mean(arr))

47.5


In [6]:
print(np.cumsum(arr))

[ 20  60 120 190]


In [7]:
print(np.cumprod(arr))

[     20     800   48000 3360000]


In [8]:
arr1 =[100,150,199,200,250,130]
arr2 =[10,50,30,40,30,10]

price = np.array(arr1)
quantity = np.array(arr2)

print(price,"\n",quantity)

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]


In [11]:
print(np.cumprod([price,quantity], axis = 0))

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]


In [14]:
c =np.cumprod([price,quantity], axis = 0)
print(c[1])

[1000 7500 5970 8000 7500 1300]


In [16]:
print(c[1].sum())

31270
