In [7]:
import numpy as np

a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print(b)
print(a+b)

c = np.array([20,30,40])
d = np.array([60,70,80])
print(c)
print(d)
print(c*d)

a = np.array([20,30,40])
b = np.array([4])
print(a)
print(b)
print(a*b)

[20 30 40]
[60 70 80]
[ 80 100 120]
[20 30 40]
[60 70 80]
[1200 2100 3200]
[20 30 40]
[4]
[ 80 120 160]


In [1]:
l1 =[20,30,40]
l2 =[50,60,70]
print(l1+l2)


[20, 30, 40, 50, 60, 70]


In [4]:
l1 =[20,30,40]
l2 =5
print(l1*l2)

[20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40]


In [8]:
a= np.array([40,50,"60"])
print(a)


['40' '50' '60']
