In [1]:
a = [30,40,50]
b = [5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [3]:
#concatenate
import numpy as np

arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [4]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2],axis = 0))

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  3]]


In [5]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2],axis = 1))

[[30 40  5  5]
 [50 60  3  3]]


In [6]:
print(np.hstack([arr1,arr2]))  #horizontal concatenation

[[30 40  5  5]
 [50 60  3  3]]


In [7]:
print(np.vstack([arr1,arr2]))  #verital concatenation 

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  3]]


In [11]:
arr1 = np.array([30,40,50,60,10,20])
print(np.array_split(arr1,3))

[array([30, 40]), array([50, 60]), array([10, 20])]


In [12]:
arr1 = np.array([30,40,50,60,10,20])
b = np.array_split(arr1,3)
print(b[1])

[50 60]


In [13]:
arr1 = np.array([[30,40,50],[60,10,20]])
b = np.array_split(arr1,3)
print(b)

[array([[30, 40, 50]]), array([[60, 10, 20]]), array([], shape=(0, 3), dtype=int64)]
