In [3]:
import numpy as np

arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1+arr2)
print(np.add(arr1,arr2))

[60 60 70 40 30]
[60 60 70 40 30]


In [4]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [40 30]]
[[60 60]
 [40 30]]


In [5]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [6]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [7]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [11]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([3])
print(np.pow(arr1,arr2))

[27 64  8  1]


In [13]:
arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))


[3. 4. 2. 1.]
